### ISSUE TITLE
can we parse bullet points into markdown automatically?

### ISSUE THREAD

**Issue by ralyodio** [balthazar/ng-markdown#14]
```
• foo
• bar
• baz

```

Should be converted to asterisk:

```
* foo
* bar
* baz
```

If I paste this text (from word, or other rich text editor), it would be cool if it were converted to markdown bulleted list automatically. Most of my users will be pasting from word or html bulleted list in their use cases.

**Comment by balthazar** [comment]
You want to convert every `•` character into a `-` or a `*` directly into the textarea ?

**Comment by ralyodio** [comment]
Yeah, basically. I forget is it \* or - for a bullet?

On Thu, Jul 10, 2014 at 5:25 AM, Apercu notifications@github.com wrote:

> You want to convert every \* character into a - or a \* directly into the
> textarea ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/Apercu/ng-markdown/issues/14#issuecomment-48597486.

## 

Anthony Ettinger
http://about.me/anthony.ettinger
anthony@ettinger.name
+1 (831) 406-1123

**Comment by balthazar** [comment]
It works the exact same way, but the `-` looks more like a list to me. If I implement this, that will be optional, maybe with a parameter like `list-transform=true` ?

PS : Wait for your PR #8 :)

**Comment by ralyodio** [comment]
Oh, that would be sweet. Yeah, I think most people would actually type *
though, not -. But if its either, just support both.

On Thu, Jul 10, 2014 at 5:44 AM, Apercu notifications@github.com wrote:

> It works the exact same way, but the - looks more like a list to me. If I
> implement this, that will be optional, maybe with a parameter like
> list-transform=true ?
> 
> PS : Wait for your PR #8 https://github.com/Apercu/ng-markdown/pull/8 :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/Apercu/ng-markdown/issues/14#issuecomment-48599189.

## 

Anthony Ettinger
http://about.me/anthony.ettinger
anthony@ettinger.name
+1 (831) 406-1123

**Comment by balthazar** [comment]
Yeah the editor support both, but for your transformation, I 'll not use the `*` : if you have a close look, you will see that it is like 2 or 3px upper than the `-`, so not well centered with the text.
