### ISSUE TITLE
Is there a way to access showdown to add extensions?

### ISSUE THREAD

**Issue by handonam** [balthazar/ng-markdown#24]
I wanted to create an extension to showdown that does this:
https://github.com/showdownjs/showdown/issues/238

However, I'm not sure how we'd be able to modify the options for showdown.  I just wanted to bold/italicize/link my text. any thoughts?

**Comment by balthazar** [comment]
Hi,

Sorry, but this directive does not uses showdown ;)

**Comment by handonam** [comment]
ah apologies!  I referenced the wrong project :)
