### ISSUE TITLE
avoid using inline styles

### ISSUE THREAD

**Issue by ralyodio** [balthazar/ng-markdown#5]
It makes it more difficult to re-style because you're using inline styles.

**Comment by balthazar** [comment]
Where ? On the `textarea` element ?

**Comment by ralyodio** [comment]
Yeah. everything should be handled by a class and defined in CSS file.

**Comment by balthazar** [comment]
I know, that's partially why I reformat a lot of code inside the editor script. These inline style comes from the `elastic` directive that allow the textarea to resize automatically depending on it's content.

Since the calculations are done in Javascript, there is no other way I think

**Comment by ralyodio** [comment]
Is there anyway to disable that elastic feature?

-- Anthony

**Comment by balthazar** [comment]
Not for now, but I'm working on it
