### ISSUE TITLE
provide unminified versions in ./dist for bower package

### ISSUE THREAD

**Issue by ralyodio** [balthazar/ng-markdown#9]
ideally, it would not be in a subdirectory of the bower package, it should be in the root. both minified and unminified versions.

**Comment by balthazar** [comment]
I want to keep the repo as clean as possible, that's why I organised everything in folders.

For the unminified versions, did you talk about the compiled `.css` and the concaneted `.js` file that contains all the Markdown files and the directive ? I can eventually create a task to generate it, but it will be in the dist folder.

**Comment by ralyodio** [comment]
The yeoman build generator expects libs to be in root, not a subdir.

**Comment by balthazar** [comment]
Hum can you please give the source for this ? Will go for it if it's the general convention

**Comment by ralyodio** [comment]
I don't recall where I read this, I think it was on the angulare-fullstack generator issues somewhere. All I can tell you is if the source files aren't in the root dir, then it doesn't get picked up by that generator.

**Comment by balthazar** [comment]
Have you already experienced this issue ? Using the angular-fullstack generator 1.4.3, never had this problem.

It takes the content of the `package.json` to inject the dependencies in the `index.html`, I referenced the good paths in it so all should work well.

Anyway I'll test it with the new 2.0 release to see if it still works

**Comment by ralyodio** [comment]
Yes. I have it on all bower scripts where the file is not in root. You have to statically include them and they don't become part of vendor.js

-- Anthony

**Comment by balthazar** [comment]
Interesting, could you please link me the concerned scripts and / or the project generated with angular-fullstack you had the issue ?

**Comment by ralyodio** [comment]
My project isn't on github. But here's the index.html from that generator project I'm using:

```
<!-- build:js(app) scripts/vendor.js -->
<!-- bower:js -->
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-resource/angular-resource.js"></script>
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-route/angular-route.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/angular-markdown-directive/markdown.js"></script>
<script src="bower_components/angular-animate/angular-animate.js"></script>
<script src="bower_components/moment/moment.js"></script>
<script src="bower_components/angular-moment/angular-moment.js"></script>
<script src="bower_components/i18next/i18next.js"></script>
<script src="bower_components/i18ng/i18ng.js"></script>
<script src="bower_components/lodash/dist/lodash.compat.js"></script>
<script src="bower_components/angular-elastic/elastic.js"></script>
<!-- endbower -->
<!-- endbuild -->

<!-- static js includes -->
<script src="bower_components/showdown/compressed/showdown.js"></script>
<script src="bower_components/ng-markdown/dist/ng-markdown.min.js"></script>
<!-- end static includes -->
```

**Comment by balthazar** [comment]
Very strange behavior, have you also the problem with `jquery` and `lodash` or not ?

I just generated a [project](https://github.com/Apercu/fullstack) using the angular-fullstack generator 2.0.2 and everything work just as expected. Did you run the `bower install` with `--save` option ?

**Comment by ralyodio** [comment]
Yes. I did. There seems to be a problem with certain scripts. Yours was one of them. Showdown.js was the other problematic one. The guys over on that generator said its because its not in the root directory.
